name: Deploy Backend (Vercel) and Frontend (GitHub Pages)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

  deploy-backend:
    needs: prepare
    runs-on: ubuntu-latest
    if: ${{ secrets.VERCEL_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel (if VERCEL_TOKEN present)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Install vercel CLI locally
          npm i -g vercel
          # Deploy (this creates a deployment and prints URL)
          vercel --prod --confirm --token $VERCEL_TOKEN

  build-and-deploy-frontend:
    needs: [prepare, deploy-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Build with BACKEND_URL
        env:
          REACT_APP_CONTACT_ENDPOINT: ${{ secrets.BACKEND_URL }}
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
